# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Victor
title: Biólogo
email: assiz.christian@gmail.com
#phone: Your phone number (optional)
#cv   : "resume.pdf"
website: http://znt.art.br/ej

# Social links
#twitter_username: jekyllrb
#github_username:  moya10
#dribbble_username: jekyll
facebook_username: chris.assiz
#flickr_username: jekyll
instagram_username: chris_assiz
linkedin_username: christianangelideassiz
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
# about_title: Sobre Mim (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Biólogo em busca de uma nova oportunidade de trabalho na área. Tenho conhecimentos em ecologia e preservação de espécie, para realizar avaliações de impacto ambiental e inventário de fauna e flora. ExperiÊncia em realizar mapas pra Sistemas Integrado de Georeferenciamento e trabalhos que necessitam desenvolver mapas aeroespacial para diversos propósitos.  
 
#  You can even add paragraphs by using empty lines like this and add anything else markdown supports such as

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)
about_logo_image: images/eeji2.jpg
# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
    - **Curso** "Manejo de Fauna Silvestre e Exótica | *IBIMM - Instituto de Biologia Marinha e Meio Ambiente* 
    - **Curso** "Biologia Marinha e Ecossistemas Costeiros" | *UNESP - Núcleo de Estudos em Biologia, Ecologia e Cultivo de Crustáceos*
    - **Curso** "Sistema de Informações Geográficas" | *Universidade do Estado de Minas Gerais*
# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "makefile",
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
